---
name: CI
on: [push]

jobs:
  main:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go mod download
      - run: '[[ -z $(go fmt ./...) ]]'
      - run: make test
